In [2]:
import numpy as np

Criando uma array

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr
type(arr) #Mostra o tipo da variável

numpy.ndarray

Mostra a versão da library

In [4]:
np.__version__

'1.23.3'

Criando array com uma lista e um tuple

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr = np.array((1, 2, 3, 4, 5))

Criando uma 0-D Array

In [6]:
arr = np.array(42)

arr

array(42)

1-D Array

In [7]:
arr  = np.array([1, 2, 3, 4, 5])

arr

array([1, 2, 3, 4, 5])

2-D Array

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

3-D Array

In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Checando o número de dimensões

In [10]:
a = np.array(42)
b  = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays

In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions: 5


Acess Array Elements

In [12]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


Getting two array elements

In [13]:
print(arr[2] + arr[3])

7


Access 2-D Arrays

In [14]:
arr = np.array([[1,2,3,4,5], [6,5,7,8,9]])

print(arr[0, 1]) #Print 2nd element on 1st row

2


Access 3-D Arrays

In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


Negative Indexing

In [16]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, -1])

10
